# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-nJTML5P69opXYTPQZ3XOQa7VtPnT26
"""

import streamlit as st
import pandas as pd
import joblib

# ==========================
# Page Configuration
# ==========================
st.set_page_config(
    page_title="Resume Screening System",
    page_icon="📄",
    layout="wide"
)

# ==========================
# Load Saved Files
# ==========================
model = joblib.load("resume_model.pkl")
scaler = joblib.load("scaler.pkl")
feature_names = joblib.load("feature_names.pkl")

st.title("📄 AI Resume Screening System")

st.write("Predict whether a candidate is likely to be **Hired** or **Rejected**.")