# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-nJTML5P69opXYTPQZ3XOQa7VtPnT26
"""

import streamlit as st
import pandas as pd
import joblib

# ==========================
# Page Configuration
# ==========================
st.set_page_config(
    page_title="Resume Screening System",
    page_icon="📄",
    layout="wide"
)

# ==========================
# Load Saved Files
# ==========================
model = joblib.load("resume_model.pkl")
scaler = joblib.load("scaler.pkl")
feature_names = joblib.load("feature_names.pkl")

st.title("📄 AI Resume Screening System")

st.write("Predict whether a candidate is likely to be **Hired** or **Rejected**.")

st.header("Candidate Information")

col1, col2 = st.columns(2)

with col1:
    job_role = st.selectbox(
        "Job Role",
        [
            "AI Researcher",
            "Cybersecurity Analyst",
            "Data Scientist",
            "Software Engineer"
        ]
    )

    education = st.selectbox(
        "Education",
        [
            "B.Sc",
            "B.Tech",
            "M.Tech",
            "MBA",
            "PhD"
        ]
    )

    experience = st.number_input(
        "Experience (Years)",
        min_value=0,
        max_value=30,
        value=2
    )

    projects = st.number_input(
        "Projects Count",
        min_value=0,
        max_value=20,
        value=2
    )

with col2:

    english = st.selectbox(
        "English Level",
        [
            "Beginner",
            "Intermediate",
            "Advanced"
        ]
    )

    certification = st.selectbox(
        "Certification",
        [
            "None",
            "AWS Certified",
            "Azure AI",
            "Deep Learning Specialization",
            "Google ML",
            "Security+"
        ]
    )

    skill_match = st.slider(
        "Skill Match Percentage",
        0,
        100,
        60
    )

    salary = st.number_input(
        "Expected Salary",
        min_value=10000,
        max_value=500000,
        value=50000
    )

    skills = st.multiselect(
    "Skills",
    [
        "Python",
        "SQL",
        "Java",
        "C++",
        "Machine Learning",
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "NLP",
        "Transformers",
        "Git",
        "Linux",
        "Networking",
        "Cybersecurity",
        "Ethical Hacking",
        "SIEM",
        "Pandas",
        "React",
        "Scikit-learn"
    ]
)

predict = st.button("Predict Candidate")