# -*- coding: utf-8 -*-
"""train.model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQ3dXi9zpGw1AP3DZlRuFvdibfMNIaMT
"""

import numpy as np
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Resume_Screening.xlsx')
df.head()

df.drop("Candidate_ID", axis=1, inplace=True, errors='ignore')
df

df["Certifications"] = df["Certifications"].fillna("None")
df["Certifications"].isnull().sum()

df["Recruiter_Decision"] = df["Recruiter_Decision"].map({
    "Hire": 1,
    "Reject": 0
})
df["Recruiter_Decision"].unique()

df["English_Level"] = df["English_Level"].map({
    "Beginner":0,
    "Intermediate":1,
    "Advanced":2
})
print(df["English_Level"].head())
print(df["English_Level"].dtype)
print(df["English_Level"].unique())

df = pd.get_dummies(df, columns=["Job_Role"], dtype=int)
df = pd.get_dummies(df, columns=["Education"], dtype=int)
df = pd.get_dummies(df, columns=["Certifications"], dtype=int)

from sklearn.preprocessing import MultiLabelBinarizer
df['Skills']=df['Skills'].str.split(',')
df['Skills']=df['Skills'].apply(lambda x:[skill.strip() for skill in x])
mlb= MultiLabelBinarizer()
skills_df= pd.DataFrame(
    mlb.fit_transform(df['Skills']),
    columns=mlb.classes_,
    index=df.index
)
df=pd.concat([df.drop('Skills',axis=1),skills_df],axis=1)

df.info()

X = df.drop("Recruiter_Decision", axis=1)
Y = df["Recruiter_Decision"]

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("Data Scaling Completed Successfully!")

from sklearn.linear_model import LogisticRegression
model= LogisticRegression(max_iter=2000)
model.fit(X_train,Y_train)
print("Model Trained Successfully!")

import joblib

joblib.dump(model, "resume_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "feature_names.pkl")

print("Files Saved Successfully!")

import os

print(os.listdir())

Y_pred=model.predict(X_test)

from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(Y_test,Y_pred))
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,Y_train)

Y_pred_dt=dt.predict(X_test)
from sklearn.metrics import accuracy_score
print("Decision Tree Accuracy:", accuracy_score(Y_test,Y_pred_dt))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, Y_train)

Y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(Y_test, Y_pred_rf))

from google.colab import files

files.download("resume_model.pkl")
files.download("scaler.pkl")
files.download("feature_names.pkl")